질문별 상세보기 API
dnd-side-project/dnd-10th-6-backend pull request #53
Opened 2024-02-21 14:34 UTC by rlacksgus97

## 요약
질문별 상세보기 API

## 변경된 점
- 필터 구현을 위해서 Period, Relation에 각각 TOTAL enum을 추가했습니다.

## 특이 사항
- projection 적용은 추후 구현
- createdAt, updatedAt 추가되면 response에 작성 일자 포함해야 함

2024-02-21 16:32 UTC, eun-seong requested changes
수고하셨습니다😎
옵션 응답하는 부분 논의 완료되면 승인할게요!

2024-02-21 16:32 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/domain/survey/AnswerController.java
> +            @RequestParam(name = "relation", required = false, defaultValue = "TOTAL") String relation,
```suggestion
            @RequestParam(name = "period", required = false, defaultValue = "TOTAL") Period period,
            @RequestParam(name = "relation", required = false, defaultValue = "TOTAL") Relation relation,
```

stringToEnumConverter가 있어서 enum 타입으로 자동으로 변환됩니다!

2024-02-21 16:32 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java
> +    // TODO: 작성 날짜 포함해야 함
#33 과 연결해서 작업하면 되겠어요!

2024-02-21 16:32 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
> +        if (!period.equals(Period.TOTAL)) {
```suggestion
        if (!period.isTotal()) {
```
이 함수를 추가하고 메소드를 호출하는게 어떨까요?

```java
    public boolean isTotal() {
        return this == TOTAL;
    }
```

2024-02-21 16:32 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
> +                            .answer(answerOfQuestion.getAnswer())
answer에 들어가는 값이 2가지인데요.
OPTION타입일 경우 -> optionId
MANUAL타입일 경우 -> 사용자가 입력한 값

현재 로직으로 가면 프론트에서 문항 조회 api를 쏴야 한다는... 점이 있구요, 옵션타입일 경우 해당 옵션의 텍스트로 바꿔치기해서 응답한다면 프론트에서는 이 api 하나만 호출하면 됩니다.

저희가 정책을 정하면 될 것 같은데요.
설문 조회할 때마다 api 호출하는 것보다 answer에 question을 가지고 있으니까, 서버쪽에서 옵션의 text로 바꿔주는 게 좋지 않을까 란 생각입니다.

2024-02-22 10:15 UTC, eun-seong commented
이후 PR 머지하면서 컨플릭트 발생했습니다. 리베이스 한 번 부탁드려요!

2024-02-23 08:34 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
> +        return new GetAnswersByQuestionResponse(question.getTitle(), answers);
cursor를 사용하지 않아서 프론트에서 마지막 페이지라는 것을 알 수 있는 필드가 필요합니다.
PaginationResponse dto를 하나 두고, 현재 응답한 페이지와 사이즈 그리고 전체 페이지 개수를 함께 응답해야 할 것 같아요.

```suggestion
        return new GetAnswersByQuestionResponse(question.getTitle(), PageableDto.create(answers));
```

아래 dto 만들어서 사용하면 되지 않을까 싶습니다:)
`surveys.get()`을 하지 않고 바로 `surveys.map()` 사용하면 Page 그대로 유지할 수 있어요!

```java
@Getter
@AllArgsConstructor
public class PageableDto<T> {
    private List<T> content;
    private int page;
    private int size;
    private int totalPage;
    private long totalCount;

    public static <T> PageableDto<T> create(Page<T> data) {
        return new PageableDto<>(
                data.getContent(),
                data.getPageable().getPageNumber(),
                data.getSize(),
                data.getTotalPages(),
                data.getTotalElements()
        );
    }

}
```

2024-02-23 13:47 UTC, rlacksgus97 commented on src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
> +                            .answer(answerOfQuestion.getAnswer())
옵션타입일 경우 해당 옵션의 텍스트로 바꿔치기해서 응답하는 방식으로 수정하겠습니다.

2024-02-23 15:50 UTC, eun-seong approved these changes
🥹 수고하셨습니다..

2024-02-23 15:51 UTC, merged