JWT 토큰 인증 구현(refresh 진행중)
dnd-side-project/dnd-10th-6-backend pull request #6
Opened 2024-02-05 15:49 UTC by rlacksgus97

## 요약
Spring Security 적용을 고민하다가 우선 제외하고 구현했습니다.

- [ ] JwtProvider로 토큰 발행 및 검증
- [ ] JwtFilter 적용
- [ ] refresh 로직

## 변경된 점
1. JwtProvider로 토큰 발행 및 검증
- OAuthProvider, OAuthId로 claim 생성
2. JwtFilter 적용
- permittedURIs로 필터 예외 경로 지정

## 특이 사항
- application-local.yml 업데이트 했습니다.
- claim에서 얻은 정보를 어떻게 관리해야할지 고민중인데, 혹시 좋은 방법이 있을까요?
- refresh는 금방 마무리해두겠습니다..ㅜ

2024-02-05 17:38 UTC, eun-seong requested changes
늦은 시간까지 수고하셨습니다🥹👍

JWT Claim을 담는 부분은 변경이 꼭 필요할 것 같고, 나머지는 코멘트 보시고 찬현님이 결정 해주시면 될 것 같아요😄
refreshToken 부분도 완료되면 다시 리뷰 요청 부탁드립니다!

2024-02-05 17:38 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/jwt/JwtProvider.java
> +    }
`createToken()`은 `claim`과 `validTime`만 받고, `build()` 메소드를 따로 두어도 좋을 것 같아요!
secretKey와 header 등 공통되는 부분이 있어서요.

2024-02-05 17:38 UTC, eun-seong commented on src/test/java/com/dnd/namuiwiki/jwt/JwtProviderTest.java
> +@SpringBootTest
오 테스트 코드를 작성하셨군요! 저는 잊고 있었네요.. #4 테스트 코드는 나중에 추가해두겠습니다.

JwtProvider를 테스트하는데 `@SpringBootTest` 사용하신 이유가 있을까요??
유닛테스트로 진행해도 충분한 클래스인 것 같아서 여쭈어요. 
mock객체를 쓰는데 정말 어렵긴 하지만(저한테).. mocking 라이브러리 추가해서 시도해보는 게 어떨까요??

2024-02-05 17:38 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/jwt/JwtFilter.java
> +public class JwtFilter implements Filter {
```suggestion
public class JwtFilter implements OncePerRequestFilter {
```

인증은 한 번만 진행해도 되는 필터라 `OncePerRequestFilter`를 상속해도 좋을 것 같아요 ㅎㅎ

2024-02-05 17:38 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/jwt/JwtFilter.java
> +                throw new ApplicationErrorException(ApplicationErrorType.NOT_FOUND_ACCESS_TOKEN);
예외가 필터에서 터지면 스프링에서 디폴트로 처리하게 되어서, try catch로 response를 직접 설정해주거나 FilterExceptionHandler 필터를 하나 더 두어야 할 것 같아요.
인지하고 계실 수 있지만 리마인드 겸 말씀드립니다!

2024-02-06 16:30 UTC, eun-seong commented
테스트해봤는데, `LoginResponseDto`에 getter가 없어서 json 파싱 에러가 발생합니다.
`@Getter` 추가해주셔요!

2024-02-06 16:33 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/jwt/LoginResponseDto.java
> +public class LoginResponseDto {
테스트해봤는데, getter가 없어서 json 파싱 에러 발생합니다!

```suggestion
@Getter
public class LoginResponseDto {
```

2024-02-07 11:44 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/jwt/JwtFilter.java
> +        if (permittedURIs.stream().noneMatch(p -> antPathMatcher.match(p, request.getRequestURI()))) {
preflight로 날라오는 options까지 헤더 인증을 거치고 있어서 브라우저에서 요청이 실패하게 되네요!
http method가 "OPTIONS"일 경우 검증하지 않게 처리가 필요하겠습니다.

2024-02-07 14:24 UTC, rlacksgus97 commented on src/main/java/com/dnd/namuiwiki/jwt/LoginResponseDto.java
> +public class LoginResponseDto {
일단 패키지 구조를 바꾸고 싶어서 기능별로 대충 묶어뒀습니다..!

2024-02-08 15:05 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/jwt/JwtProvider.java
> +    }
claims와 validTime으로 토큰 빌드하는 메소드를 분리하면 나중에 페이로드에 값이 추가되었을 때 더 유연하게 대처할 수 있을 것 같아요!

```suggestion
    public String createAccessToken(String wikiId) {
        Claims claims = Jwts.claims()
                .subject("accessToken")
                .add(WIKI_ID, wikiId)
                .build();
        return createToken(refreshTokenValidTime, claims);
    }

    public String createRefreshToken() {
        Claims claims = Jwts.claims()
                .subject("refreshToken")
                .build();
        return createToken(refreshTokenValidTime, claims);
    }

    private String createToken(Long validTime, Claims claims) {
        Date now = new Date();
        return Jwts.builder()
                .issuedAt(now)
                .header()
                .add("typ", "JWT")
                .add("alg", "HS256")
                .and()
                .claims()
                .add(claims)
                .and()
                .expiration(new Date(now.getTime() + validTime))
                .signWith(secretKey)
                .compact();
    }
```

2024-02-08 15:09 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/jwt/JwtProvider.java
> +                    .add(WIKI_ID, wikiId)
페이로드에는 userId가 들어가야 하지 않을까요?
wikiId는 외부 노출이 가능한 public한 id이고, userId는 jwt 인증용으로 사용하는 id라고 생각했습니다.

2024-02-09 09:26 UTC, merged

2024-02-09 14:19 UTC, rlacksgus97 commented on src/main/java/com/dnd/namuiwiki/jwt/JwtProvider.java
> +                    .add(WIKI_ID, wikiId)
userId는 db에 저장된 pk를 뜻하시는 건가요?

2024-02-09 14:28 UTC, eun-seong commented on src/main/java/com/dnd/namuiwiki/jwt/JwtProvider.java
> +                    .add(WIKI_ID, wikiId)
네 맞습니다!